version: '3.7'
services:
  fastapi:
    build: ./ 
    ports:
      - 8000:8000
    environment:
      - PG_HOST=database
      - PG_DATABASE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres 
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres

  database:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
    postgres_data:
